spring:spring.jpa.properties.javax.persistence.schema-generation.scripts.action
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb
    username: root
    password: root
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scrupts:
              action: create
              create-targer: db_create.sql